version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8040:80"
    depends_on:
      - db

  db:
    image: mysql:8.0.36
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: lab03
      MYSQL_USER: user
      MYSQL_PASSWORD: password
